# This file contains values from Cookiecutter

default_context:
  project_name: "pcgaw"
  project_description: "python chatgpt API wrapper"
  organization: "thamognya"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.11
  github_name: "thamognya"
  email: "contact@thamognya.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
